# _default:
#   type: dir/node
#   source: gitlab/link/local
#   name
#   icon
#   link
#   desc

_default:
  type: node
  source: iframe

tinyjs-plugin-ui:
  name: ui
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-ui/0.2.0/index.js
  desc: UI 插件，快速创建按钮、富样式DOM等
  image: https://zos.alipayobjects.com/rmsportal/nJBojwdMJfUqpCWvwyoA.png

tinyjs-plugin-extract:
  name: extract
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-extract/1.1.0/index.js
  desc: 画布扩展，获取画布的：Image 对象、base64 格式的图片、像素值等等
  image: https://zos.alipayobjects.com/rmsportal/nJBojwdMJfUqpCWvwyoA.png

tinyjs-plugin-audio:
  name: audio
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-audio/1.2.0/index.js
  desc: Tiny.js 音效插件
  image: https://gw.alipayobjects.com/zos/rmsportal/zMJQKshtlGCcVfGJcpvk.jpg

tinyjs-plugin-bitmap-text:
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-bitmap-text/0.1.0/index.js
  desc: 位图文字
  image: https://gw.alipayobjects.com/zos/rmsportal/phHqiahVFMthpTCIGPBz.png

tinyjs-plugin-scroller:
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-scroller/0.1.0/index.js
  desc: 滚动插件
  video: http://p.tb.cn/rmsportal_8509_scroll.mov

tinyjs-plugin-accessibility:
  name: accessibility
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-accessibility/0.0.1/index.js
  desc: 提供给特殊人群的可访问性渲染插件
  image: https://zos.alipayobjects.com/rmsportal/nJBojwdMJfUqpCWvwyoA.png

tinyjs-plugin-tiling:
  name: tiling
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-tiling/0.1.0/index.js
  desc: A fast way of rendering a tiling image
  video: http://p.tb.cn/rmsportal_8509_tile.mov

tinyjs-plugin-dust:
  cdn: https://gw.alipayobjects.com/os/lib/tinyjs-plugin-dust/0.1.5/index.js
  desc: 简单粒子
  video: http://p.tb.cn/rmsportal_8509_dust.mov

tinyjs-plugin-mesh:
  name: mesh
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-mesh/1.0.0/index.js
  desc: 网格插件
  video: https://gw.alipayobjects.com/os/rmsportal/rfKURkKcjYxfesbTesGi.mp4

tinyjs-plugin-particles:
  name: particles
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-particles/0.1.0/index.js
  desc: A really fast type of the Container built solely for speed
  image: https://gw.alipayobjects.com/zos/rmsportal/brKZyDOVAeAWANqnORVf.png

tinyjs-plugin-keyboard:
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-keyboard/0.1.0/index.js
  desc: 键盘控制
  image: https://gw.alipayobjects.com/zos/rmsportal/NocaNAexyTeRSjEQBfxl.png

tinyjs-plugin-dragonbones:
  git: https://github.com/qingyangmoke/tinyjs-plugin-dragonbones
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-dragonbones/0.1.10/index.js
  desc: 骨骼动画
  video: https://gw.alipayobjects.com/os/rmsportal/gomMEXFhlFaMOQBpWNKN.mp4

tinyjs-plugin-p2:
  name: Physics.P2
  git: https://github.com/qingyangmoke/tinyjs-plugin-p2
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-p2/0.1.4/index.js
  desc: 基于 P2 物理引擎
  video: https://gw.alipayobjects.com/os/rmsportal/FezkCDQzUdhPPQTzDiuu.mp4

tinyjs-plugin-ant:
  name: Physics.Ant
  git: https://github.com/qingyangmoke/tinyjs-plugin-ant
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-ant/0.1.2/index.js
  desc: 基于 ant 简单版物理引擎
  video: https://gw.alipayobjects.com/os/rmsportal/mPNzPmPpZOvMYKwHNeVI.mp4

tinyjs-plugin-worldwrap:
  name: worldwrap
  git: https://github.com/qingyangmoke/tinyjs-plugin-worldwrap
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-worldwrap/0.1.1/index.js
  desc: world wrap plugin
  image: https://zos.alipayobjects.com/rmsportal/nJBojwdMJfUqpCWvwyoA.png

tinyjs-plugin-weapon:
  git: https://github.com/qingyangmoke/tinyjs-plugin-weapon
  cdn: https://gw.alipayobjects.com/as/g/tiny-plugins/tinyjs-plugin-weapon/0.1.1/index.js
  desc: 武器发射系统
  image: https://zos.alipayobjects.com/rmsportal/nJBojwdMJfUqpCWvwyoA.png
