_default:
  type: node
  source: github

README:
  uri: tinyjs-cli
  name: 本地开发工具
  link: ant-tinyjs/tinyjs-cli:README.md

tinyjs-resource-loader:
  name: 游戏资源 webpack loader
  link: ant-tinyjs/tinyjs-resource-loader:README.md

tinyjs-types:
  name: 「API 提示」和「类型校验」
  link: stonelee/tinyjs-types:README.md
